require('dotenv').config();
require('./server-hotfix.js');
require('./admin-nav-hotfix.js');
require('./public-nav-hotfix.js');
require('./quiz-layout-hotfix.js');
require('./customer-account-contrast-hotfix.js');
require('./customer-portal-api-v2.js');
require('./site-route-map.js');
require('./server.js');
